### ISSUE TITLE
Vulnerabilities for npm packages are not fetched

### ISSUE THREAD

**Issue by flopes89** [Inedo/inedox-sonatype#8]
It seems that npm feeds are not considered when fetching vulnerabilities.

I suspect it's simply missing [here](https://github.com/Inedo/inedox-sonatype/blob/master/Sonatype/InedoExtension/VulnerabilitySources/OSSIndexVulnerabilitySource.cs#L182) and [here](https://github.com/Inedo/inedox-sonatype/blob/master/Sonatype/InedoExtension/VulnerabilitySources/OSSIndexVulnerabilitySource.cs#L217).

**Comment by gdivis** [comment]
You're right - missed it in both places. The fixed version is being deployed now.
